### ISSUE TITLE
Error while installing imagemagick

### ISSUE THREAD

**Issue by jrasband** [tlk/homebrew-imagemagick-x11#1]
Hi! I'm incredibly grateful that you took it upon yourself to try to solve the exact problem I am now facing with imagemagick not automatically installing with X11 support on Mac OS. I followed the directions in the README exactly, and everything worked well until the last step, when I `brew install` your tap. It seemed to work until `===> make install`. The error printout was long and I don't understand much of it, to be honest, so I'll upload it as a file:
[error.txt](https://github.com/tlk/homebrew-imagemagick-x11/files/4808496/error.txt)
There appears to be only one error, at the end, that reads `coders/heic.c:945:9: error: use of undeclared identifier 'heif_compression_AVIF';
        heif_compression_AVIF,&heif_encoder);`
After a quick web search, I see that maybe my `libheif` needs to be updated. After reinstalling `libheif` using `brew`, the error persists. At this point, I think I definitely don't understand enough about the problem to fix it.

**Comment by tlk** [comment]
Hi! Thank you for reporting this. Looks like a bug that was fixed in https://github.com/ImageMagick/ImageMagick/pull/2105 and I have updated this x11 formula accordingly. Did that solve the issue?

**Comment by jrasband** [comment]
That solved the issue! Thanks!
