### ISSUE TITLE
Calling depends_on :x11 is deprecated

### ISSUE THREAD

**Issue by ThatIsAPseudo** [tlk/homebrew-imagemagick-x11#2]
When I run `brew upgrade`, I get the following warning :
```sh
Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the tlk/imagemagick-x11 tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/tlk/homebrew-imagemagick-x11/Formula/imagemagick.rb:31
```
Is this something I need to worry about ?

**Comment by tlk** [comment]
Thanks for reporting. I am looking for a workaround.

**Comment by tlk** [comment]
Turns out the :x11 requirement is now deprecated as of https://github.com/Homebrew/brew/pull/9403

See also https://github.com/Homebrew/homebrew-core/issues/64166

**Comment by tlk** [comment]
I have replaced  `depends_on :x11` with `depends_on "libx11"` and the formula seems to work again with XQuartz being installed as a homebrew cask. Need to check up on the direction of the homebrew project.

**Comment by ThatIsAPseudo** [comment]
Thanks for reacting so quickly !

**Comment by tlk** [comment]
You are most welcome. Closing this issue as it seems to have been resolved.
