### ISSUE TITLE
Can't install vips (libvips) if tlk/imagemagick is installed

### ISSUE THREAD

**Issue by gasparschott** [tlk/homebrew-imagemagick-x11#8]
==> Installing dependencies for vips: imagemagick
Error: imagemagick is already installed from tlk/imagemagick-x11!
Please `brew uninstall imagemagick` first."

Vips wants to install the default version of imagemagick, and if I uninstall your version, install default IM and vips, and then uninstall IM and reinstall yours again, vips throws the same or similar error about not finding imagemagick. Any way to fix this?

**Comment by tlk** [comment]
Sorry to hear that the formula no longer works as a drop-in replacement.

Please consider asking the Homebrew maintainers for advice over at https://github.com/orgs/Homebrew/discussions

**Comment by tlk** [comment]
Thank you for sharing possible solutions.

Feel free to copy or fork this repo if it can be helpful in any way.
Pull-requests are welcome as long as they do not break stuff.

I have not been using homebrew in a while, so I am not going to put a lot of effort into this.

Best regards,
  Thomas
